repository:
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions: {}
        code_owner_approval: true

      required_status_checks:
        strict: true
        contexts:
          - "DCO"
      enforce_admins: null

      required_linear_history: true

      restrictions:
        users: []
        apps: []
        teams: []